CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'cliente' CHECK (role IN ('admin', 'cliente')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS palettes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    colors JSONB NOT NULL,
    is_default_active BOOLEAN NOT NULL DEFAULT FALSE,
    is_dark_active BOOLEAN NOT NULL DEFAULT FALSE,
    is_colorblind_active BOOLEAN NOT NULL DEFAULT FALSE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fonts (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    family_name VARCHAR(160) NOT NULL UNIQUE,
    file_url TEXT,
    is_active_title BOOLEAN NOT NULL DEFAULT FALSE,
    is_active_subtitle BOOLEAN NOT NULL DEFAULT FALSE,
    is_active_paragraph BOOLEAN NOT NULL DEFAULT FALSE,
    title_size_px INTEGER NOT NULL DEFAULT 36 CHECK (title_size_px BETWEEN 8 AND 120),
    subtitle_size_px INTEGER NOT NULL DEFAULT 24 CHECK (subtitle_size_px BETWEEN 8 AND 120),
    paragraph_size_px INTEGER NOT NULL DEFAULT 16 CHECK (paragraph_size_px BETWEEN 8 AND 120),
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE palettes
    ADD COLUMN IF NOT EXISTS is_visible BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE fonts
    ADD COLUMN IF NOT EXISTS is_visible BOOLEAN NOT NULL DEFAULT TRUE;